fail_fast: true
repos:
  - repo: https://github.com/grantjenks/blue
    rev: v0.9.0
    hooks:
      - id: blue
        types: [python]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        types: [python]
