fail_fast: true
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff
        args: ['check', '--fix']
        language: system
        types: [python]
        stages: [commit]
      - id: ruff-format
        name: ruff-format
        entry: ruff
        args: [format]
        language: system
        types: [python]
        stages: [commit]
