fail_fast: true
repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        types: [python]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        types: [python]
  - repo: https://github.com/dskrypa/incr_version
    rev: c8628c7c9891872493022f4f6fa8ff3b60325371
    hooks:
      - id: incr_version
