# More options: https://docs.codecov.com/docs/commit-status
---
coverage:
  status:
    project:
      default:
        target: auto    # auto compares coverage to the previous base commit
        threshold: 5%   # the leniency in hitting the target
    patch:
      default:
        target: 85%
