__title__ = 'command_parser'
__description__ = 'Command Parser'
__url__ = 'https://github.com/dskrypa/command_parser'
__version__ = '2022.02.05'
__author__ = 'Doug Skrypa'
__author_email__ = 'dskrypa@gmail.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2022 Doug Skrypa'
